name: Jest and Cypress Tests

on:
    push:
      branches:
        - nextjs-version
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'          
        
      - name: Cypress run
        uses: cypress-io/github-action@v6.5.0
        with:  
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
          

        


  
